### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by artalar** [vercel/styled-jsx#688]
Hi there, styled-jsx is an interesting lib with good API, it recommended by official docs of next.js and already integrated with it (also hosted in the Vercel GH org).
But it looks a little neglected. I was created #650 and #651 a long time ago but still have no reactions. This repo has other issues without any reactions. Why it happened, is it a lack of maintainers?

**Comment by artalar** [comment]
@rauchg, @nkzawa, @leo, @giuseppeg pay attention please

**Comment by jaydenseric** [comment]
@artalar sadly, this project is not adequately maintained to be relied upon anymore. I've put many hours into into high effort suggestions and PR's that fix critical bugs, only for them to languish for months without a merge or sometimes even review:

- https://github.com/vercel/styled-jsx/pull/641
- https://github.com/vercel/styled-jsx/pull/684

These important suggestions haven't been actioned in a year:

- https://github.com/vercel/styled-jsx/issues/575
- https://github.com/vercel/styled-jsx/issues/602#issuecomment-559709655

I really gave `styled-jsx` my best shot and have pushed it to its limits over the years, but due to bugs blocking things I need to do at this point it makes the most sense to refactor projects away from `styled-jsx` to Emotion and update my UI library to use Emotion (as well as supporting Styled Components via an abstraction). Emotion will probably have bugs too from time to time, but at least they have good velocity and actively maintain the project.

**Comment by Divlo** [comment]
I find out that `styled-jsx` is the best library to work with for styling react components.
I would love to maintain the project if there are really no one having enough time to maintain the library, because I don't want to say goodbye to `styled-jsx`.

I never liked `styled-component` solution for example, but `styled-jsx` has real issues that should be fix now, maybe @giuseppeg could add motivated collaborators to the project.

**Comment by artalar** [comment]
I hope we will see some movement in the near future, I don't want the death of styled-jsx, but the current silens of mainteners looks not good.

P.S. @Divlo currently u haven't the rights to accept PRs?

**Comment by Timer** [comment]
Hi everyone! This package is still alive and we fix issues as they come up if they relate to Next.js.

Please open any bugs you may be experiencing on the Next.js issue tracker specifically, which will give them more visibility.

RFCs should also exist as a Next.js discussion as that'd draw the most attention to get the upvotes necessary to implement the feature.

I'll close this issue, but please CC me on any issues that need attention!
