### ISSUE TITLE
Dynamic styles are recalculated multiple times

### ISSUE THREAD

**Issue by ivan-kleshnin** [vercel/styled-jsx#773]
### Bug?

**[Demo Repo](https://github.com/ivan-kleshnin/styled-jsx-bug)**

#### What is the current behavior?

Dynamic styles are unnecessary recalculated multiple times (for a single component render). Here's the basic case made with create-next-app. I can miss something – because it seems like a major flaw which is easy to notice. But I couldn't find an existing issue for it. Sorry for a potential duplicate 😞 

![shot-1](https://user-images.githubusercontent.com/2128182/150123061-880e423d-9525-4a87-8b2d-d490ecc33016.png)
![shot-2](https://user-images.githubusercontent.com/2128182/150123073-65c66d97-8326-427b-873d-98d5cc08d71f.png)

As you can see from screenshots, it happens on both sides: server and client. This behavior is persistent and reproduceable with 4.x and 5.x Styled-JSX branches. I can't see any reason to reevaluate styles if their props did not change.

#### What is the expected behavior?

Dynamic styles should be recalculated only when component (re)renders.

#### Environment (include versions)

- Version of styled-jsx: 4.xx, 5.xx
- Browser: any
- OS: any

#### Did this work in previous versions?

No.

**Comment by huozhi** [comment]
It's only calculated only once for JSXStyles, it's about the way you pass down the dynamic values.

It will be compiled to sth like the thing below, to make dynamic styles to be associated with id and work.
So that you see the `getColor()` is called 3 times.

```jsx
<div className={_JSXStyle.dynamic([ ["hash", [getColor()]] ])}>
  test
  <_JSXStyle id="hash" dynamic={[getColor()]}>
    {'div.__jsx-style-dynamic-selector{color:'.concat(getColor(), "}")}
  </_JSXStyle>
</div>
```



I recommend you to change it to define the color first and reuse it in dynamic styles if you worry about the side effects in function calls like `getColor`.

```js
const color = getColor()

`div { color: ${color} }`
```
