### ISSUE TITLE
SWC Docs

### ISSUE THREAD

**Issue by ssylvia** [vercel/styled-jsx#779]
#### Do you want to request a _feature_ or report a _bug_?

Feature: Documentation about SWC usage

#### What is the current behavior?

Currently, the only way I can see to use styled-jsx with swc is to use nextjs: https://github.com/vercel/styled-jsx#using-in-nextjs. It works automatically. How can I use styled-jsx with SWC but building my own build system?

#### What is the expected behavior?
More documentation about how to use styled-jsx with swc.

**Comment by huozhi** [comment]
There's not a way to do that very conveniently yet, unless you write your own swc transformers for styled-jsx.
Next.js 12 includes styled-jsx swc transformers so you don't have to worry.

I'll close this issue as it's not able to achive in short time. But feel free to keep the discussion here.

**Comment by ivan-kleshnin** [comment]
> Next.js 12 includes styled-jsx swc transformers so you don't have to worry.

And what if I want to publish a component library (for React)? It should be NextJS agnostic.

Babel is gradually becoming obsolete. I second that it would be great to unblock this library to be used with new bundlers like `esbuild` or higher-level tools like `vite` which are much more performant and use `tsc` or `swc` instead of `babel`. 
It's technically possible to have an extra step in compilation pipeline but it adds a lot of unnecessary complexity.
