### ISSUE TITLE
Passing the styles as a * import attribute causes error

### ISSUE THREAD

**Issue by thomasryu** [vercel/styled-jsx#781]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What is the current behavior?

Importing an entire external style folder (e.g. `import * as styles from './styles.ts'`) and attempting to use a single exported const inside a style tag (e.g. `<style jsx>{styles.button}</style>` causes the following error:

```
Error: error: Expected a template literal, string or identifier inside the JSXExpressionContainer.
Read more: https://nextjs.org/docs/messages/invalid-styled-jsx-children
```

However, importing the style directly (e.g. `import { button } from './styles.ts'` and `<style jsx>{button}</style>`) works perfectly.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Button.jsx
```
import * as styles from './styles'
export const Container: React.FC = () => (
  <>
    <div className="button">
      Button
    </div>
    <style jsx>{styles.button}</style>
  </>
)

```
styles.tsx
```
export const button = css`
  .button {
    background-color: ${colors.brand.secondary};
  }
`
```

#### What is the expected behavior?

The button style should load properly.

#### Environment (include versions)

- Version of styled-jsx (or next.js if it's being used): next.js 12.0.9
- Browser: Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)
- OS: Ubuntu 20.04.2 LTS (fossa-kakuna X63)

**Comment by huozhi** [comment]
@thomasryu I think if we let use all members of import all declaration be able to stay there as children of styled-jsx would be dangerous for runtime, and hard for users to pre-detect errors in build time. Since a `MemberExpression` can be everything not only the string or JSX element, and we cannot evaluate the result of it while AST parsing. It's more safe to use `import { button } from './style'` in this way.
