### ISSUE TITLE
Document not defined

### ISSUE THREAD

**Issue by msklive** [vercel/styled-jsx#793]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What is the current behavior?
Getting the stacktrace mentioned on issue [785](https://github.com/vercel/styled-jsx/issues/785) during build step on next v12. It was not a problem on prior major versions. 

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar
This could be difficult as I myself ran across this bug at work and could not reproduce this error locally at home.

#### What is the expected behavior?
It should'nt throw the error.

#### Environment (include versions)

- Version of styled-jsx (or next.js if it's being used): Next 12.1.5
- Browser: N/A (Build issue)
- OS: Windows 10

#### Did this work in previous versions?
Yes, upto Next v11.1.4

**Comment by msklive** [comment]
I wanted to add that the issue can be solved by making these changes on [index.js](https://github.com/vercel/styled-jsx/blob/main/src/lib/stylesheet.js#L34) (Credit goes to: [abbasEbadian](https://github.com/abbasEbadian) as mentioned on issue 785)

From:
`const node = this._isBrowser && document.querySelector('meta[property="csp-nonce"]');`

To:
`const node = this._isBrowser && (typeof document !== "undefined") && document.querySelector('meta[property="csp-nonce"]');`

I could have raised a PR for this, but I can see that there is a similar [PR](https://github.com/vercel/styled-jsx/pull/769) from AaronO

**Comment by huozhi** [comment]
What environment are you using that requires extra checking for determing browser? Can you provide a minimal reproduction?

The reason we're holding #769 is because `typeof window` is widly used by many libraries need to be run in nodejs+browser, if we need to support this by changing the condition it will reflect lots of existing libraries. And any new created runtime could customize the global variables, it's better to find a way to balance it rather than changing all libraries to support a new env. But if later we really have to change it, we could adopt it.

**Comment by msklive** [comment]
I'm closing this issue. Turns out, it was a mistake from our end, some dude had reconfigured window to be an empty object at the top level -_- 
once i had fixed that, it started to work as intended.

But, what still bugs me though is that that code was written some time back and the builds were still passing up till v12. oh well...

thank you nonetheless :)
sorry abt the confusion :(
